import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './{components}/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}><Navbar /><div className='p-4  bg-emerald-50'>{children}</div></body>
    </html>
  )
}
